# ./docker-compose.yml

version: "3"

services:
  db:
    image: postgres:9.5.23-alpine
    container_name: postgres-db
    env_file:
      - ./database.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database-init/englishdbfinal.sql:/docker-entrypoint-initdb.d/englishdbfinal.sql
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
  nginx: 
    image: nginx
    container_name: nginx
    ports:
      - "80:80"      
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  postgres-data:
  database-init:
